"""001

Revision ID: 587e80b60fa9
Revises: 
Create Date: 2023-10-17 03:26:51.286127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = '587e80b60fa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', app.utils.helpers.UUID(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.utils.helpers.UUID(length=16), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('con_id', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('con_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_contacts',
    sa.Column('user_id', app.utils.helpers.UUID(length=16), nullable=False),
    sa.Column('contact_id', app.utils.helpers.UUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'contact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_contacts')
    op.drop_table('users')
    op.drop_table('contacts')
    # ### end Alembic commands ###
